Add contents to change
brainchildservices/brainchildservices pull request #13
Opened 2021-07-17 09:33 UTC by SijoGeorge7012

![image](https://user-images.githubusercontent.com/78071547/126032787-2ba28727-f65b-4104-b541-e3be4e9e1efe.png)

2021-07-17 09:58 UTC, wandercode requested changes

2021-07-17 09:58 UTC, wandercode commented on index.html
> +                    <h2 class="pa-h2-quote pa-bright fadeInDelay03Duration10"><q>To grow your business, you need the right tech team today! <br> Let us offer you the best fit. </q></h2>
please remove the q tag before and after of content paragraph

2021-07-17 10:09 UTC, wandercode approved these changes

2021-07-19 05:00 UTC, VishnuKulakkattu approved these changes
LGTM

2021-07-19 05:02 UTC, merged