assigned task done
brainchildservices/brainchildservices pull request #16
Opened 2021-07-17 13:43 UTC by vishnusandeep969

change See our work → We can build anything you want

change this “The new Style for 2021 is here. Like it? BUY THEME NOW!” →  'See our work ' (make it like the buy theme now  style)

About us, the menu button direction is now to the portfolio section. (check that) change direction to the about us section.

change the website title → Brainchild Services

![image](https://user-images.githubusercontent.com/80237613/126038945-9ed6e7a6-62af-48bc-8109-f74d03467746.png)

2021-07-17 16:34 UTC, wandercode requested changes

2021-07-17 16:34 UTC, wandercode commented on index.html
> +                        <p class="pa-p-v2 pa-bright fadeInLeftDelay03Duration10"><a href="https://themeforest.net/item/particle-modern-tech-startup-html-template/20078383?ref=Skilltech" target="_blan
please change the href address null -->#

2021-07-19 04:37 UTC, vishnusandeep969 commented
changes done

2021-07-19 04:44 UTC, wandercode commented
LGTM 👍

2021-07-19 04:45 UTC, VishnuKulakkattu approved these changes
LGTM

2021-07-19 04:50 UTC, wandercode approved these changes

2021-07-19 04:53 UTC, merged