logo added and navbar menu item fixed
brainchildservices/brainchildservices pull request #2
Opened 2021-07-13 13:04 UTC by SijoGeorge7012

![image](https://user-images.githubusercontent.com/78071547/125456371-7069df3c-2bab-4439-aa9c-eb99f1d509ce.png)
![image](https://user-images.githubusercontent.com/78071547/125456474-f9461b81-cfc5-448c-8ed3-decbc3633062.png)
![image](https://user-images.githubusercontent.com/78071547/125456525-c0823db6-8149-4026-a4b9-d813c16d6afb.png)

2021-07-13 14:00 UTC, rohithkrajan commented on assets/css/particle-theme.css
> +/* MY CSS PROPERTYS*/
do not put comment in ou project source code as my css property

2021-07-13 14:01 UTC, rohithkrajan commented on dark-index.html
> +	<a class="pa-mobile-main-logo" href="#" id="logo1"><img alt="" src="assets/images/logo.png">BRAINCHILD TECHNOLOGY</a>
id should not be given as logo1, 2 etc. Please choose names correctly

2021-07-13 14:01 UTC, rohithkrajan commented on dark-index.html
> +				<a class="pa-mobile-navbar-brand" href="#"><img alt="" src="assets/images/logo.png"></a>
Please always put an alt for an image

2021-07-13 14:32 UTC, rohithkrajan requested changes
added comments

2021-07-15 04:29 UTC, SijoGeorge7012 commented on assets/css/particle-theme.css
> +/* MY CSS PROPERTYS*/
can i change this name to LOGO & NAVBAR CSS PROPERTIES   ?

2021-07-15 04:38 UTC, SijoGeorge7012 commented on dark-index.html
> +	<a class="pa-mobile-main-logo" href="#" id="logo1"><img alt="" src="assets/images/logo.png">BRAINCHILD TECHNOLOGY</a>
Here can i change this name to brainchildlogo  ?

2021-07-15 04:38 UTC, SijoGeorge7012 commented on dark-index.html
> +				<a class="pa-mobile-navbar-brand" href="#"><img alt="" src="assets/images/logo.png"></a>
ok

2021-07-15 04:50 UTC, rohithkrajan commented on assets/css/particle-theme.css
> +/* MY CSS PROPERTYS*/
yes

2021-07-15 04:50 UTC, rohithkrajan commented on dark-index.html
> +	<a class="pa-mobile-main-logo" href="#" id="logo1"><img alt="" src="assets/images/logo.png">BRAINCHILD TECHNOLOGY</a>
yes something meaningful in the context

2021-07-15 04:51 UTC, rohithkrajan commented on dark-index.html
> +				<a class="pa-mobile-navbar-brand" href="#"><img alt="" src="assets/images/logo.png"></a>
alt is basically the text content of what is the image. so you can just put brainchild services logo

2021-07-15 04:54 UTC, SijoGeorge7012 commented on dark-index.html
> +				<a class="pa-mobile-navbar-brand" href="#"><img alt="" src="assets/images/logo.png"></a>
ok

2021-07-15 05:49 UTC, rohithkrajan approved these changes
LGTM

2021-07-15 06:08 UTC, wandercode approved these changes

2021-07-15 06:09 UTC, merged